server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://r-austria_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: r-austria-bot-logs
          __path__: /logs/*.log