apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  discordToken: {{ $.Values.apiKeys.discord.token | b64enc }} # b64enc is needed, because a stringData secret field cannot hold numeric values
  youtubeApiKey: {{ $.Values.apiKeys.youtube.apiKey | b64enc }}
  twitchClientId: {{ $.Values.apiKeys.twitch.clientId | b64enc }}
  twitchSecret: {{ $.Values.apiKeys.twitch.secret | b64enc }}
  openWeatherMapApiKey: {{ $.Values.apiKeys.openWeatherMap.apiKey | b64enc }}