# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Execute build

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Build with Maven
        run: mvn -s settings.xml -B install --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          user: Sheldan
          token: ${{ secrets.ABSTRACTO_PAT }}
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.sheldan.dev
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Load env file
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .env
      - name: Docker build
        run: docker compose build
        env:
          REGISTRY_PREFIX: ${{ steps.dotenv.outputs.registry_prefix }}
          VERSION: ${{ steps.dotenv.outputs.version }}
      - name: Helm package and push
        working-directory: ./deployment/helm/
        run: |-
          helm package sissi
